name: Deploy Hugo site to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Setup Node.js (if needed for processing)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      
    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm install --production
        fi

    - name: Build Hugo site
      run: |
        hugo --minify --environment production
        echo "Built site successfully"
        ls -la public/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3_DOCS_AIMATRIX_COM }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3_DOCS_AIMATRIX_COM }}
        aws-region: ${{ secrets.AWS_REGION_S3_DOCS_AIMATRIX_COM }}

    - name: Deploy to S3
      run: |
        aws s3 sync public/ s3://docs.aimatrix.com/ \
          --delete \
          --cache-control "public, max-age=3600" \
          --metadata-directive REPLACE

    - name: Set S3 website configuration
      run: |
        aws s3api put-bucket-website \
          --bucket docs.aimatrix.com \
          --website-configuration '{
            "IndexDocument": {"Suffix": "index.html"},
            "ErrorDocument": {"Key": "404.html"}
          }'

    - name: Invalidate CloudFront (optional - if you have CloudFront)
      run: |
        # Uncomment and configure if you have CloudFront distribution
        # aws cloudfront create-invalidation \
        #   --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
        #   --paths "/*"

    - name: Deployment Summary
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "📋 Site URL: https://docs.aimatrix.com"
        echo "📊 Files deployed: $(find public -type f | wc -l)"
        echo "📁 Total size: $(du -sh public/ | cut -f1)"